# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno' 
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']