# Site settings
title: Alex Graham
description: 'Just another nerd in the valley...'
url: 'http://alexmgraham.github.io'
baseurl: '/'
google_analytics: 'UA-74237854-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alex Graham'
  email: alex@alexmgraham.com
  twitter_username: alexmgraham14
  facebook_username: alexmgraham
  github_username:  alexmgraham
  linkedin_username:  alexmgraham

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-gist', 'jemoji', 'jekyll-email-protect']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
